# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import musa.models


class Migration(migrations.Migration):

    dependencies = [
        ('musa', '0003_musiccollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiccollection',
            name='document',
            field=models.FileField(upload_to=musa.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='musiccollection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
